import { motion } from 'motion/react';
import { Brain, BookOpen, TrendingUp, CheckCircle, Quote } from 'lucide-react';

export function About() {
  const skills = ['Tổ chức tệp và thư mục khoa học, thao tác dữ liệu an toàn.','Tìm kiếm, chọn lọc và đánh giá độ tin cậy của nguồn học thuật.','Thiết kế prompt có vai trò, ngữ cảnh, yêu cầu và định dạng đầu ra rõ ràng.','Phối hợp nhóm qua Trello, Google Docs, Drive và Meet.','Kết hợp ChatGPT, DALL·E và Canva AI để tạo sản phẩm số.','Kiểm chứng, trích dẫn và chịu trách nhiệm với nội dung có AI hỗ trợ.'];
  return <div className="max-w-7xl mx-auto py-12 md:py-16 relative z-10">
    <header className="relative mb-20"><div className="inline-flex items-center gap-2 bg-secondary-container text-on-secondary-container px-4 py-2 rounded-full text-label-lg mb-6 -rotate-2 shadow-sm"><Brain size={18}/> Tổng kết & phát triển</div><h1 className="text-display-lg text-on-surface mb-6">Nhìn lại hành trình,<br/>sẵn sàng <span className="text-primary">tiến bước</span></h1><BookOpen size={120} className="absolute right-0 top-0 text-primary-container opacity-50 hidden md:block"/></header>
    <div className="grid grid-cols-1 md:grid-cols-12 gap-8 mb-24">
      <motion.div initial={{opacity:0,y:20}} animate={{opacity:1,y:0}} className="md:col-span-5 relative"><div className="absolute -inset-4 bg-primary-container rounded-2xl opacity-20 -rotate-3"/><div className="bg-surface-container-lowest p-2 rounded-2xl border border-outline-variant/30 sticker-shadow relative h-full"><img src="/previews/bai-5.png" alt="Sản phẩm thuyết trình ứng dụng AI trong giao thông" className="w-full h-full min-h-96 object-cover object-top rounded-xl"/></div></motion.div>
      <motion.div initial={{opacity:0,y:20}} animate={{opacity:1,y:0}} transition={{delay:.15}} className="md:col-span-7 flex flex-col gap-8">
        <div className="bg-surface-container-lowest p-8 rounded-3xl border border-outline-variant/30 flex-grow"><div className="flex items-center gap-3 mb-6"><div className="w-10 h-10 bg-primary-container rounded-full flex items-center justify-center"><BookOpen size={20}/></div><h2 className="text-headline-md">Kiến thức và kỹ năng đạt được</h2></div><ul className="space-y-4">{skills.map(x=><li key={x} className="flex items-start gap-3"><CheckCircle className="text-primary mt-1 shrink-0" size={20}/><span className="text-body-md">{x}</span></li>)}</ul></div>
        <div className="bg-surface-bright p-8 rounded-3xl border border-outline-variant/30"><h2 className="text-headline-md mb-4 flex items-center gap-2"><TrendingUp className="text-secondary"/>Thách thức và bài học</h2><p className="text-body-md text-on-surface-variant">Khó khăn lớn nhất là làm quen công cụ mới, tránh chỉnh sửa trùng khi cộng tác và đánh giá thông tin do AI tạo. Qua thực hành, mình học được cách phân chia nhiệm vụ rõ ràng, kiểm chứng bằng nguồn tin cậy, viết lại bằng tư duy cá nhân và công khai phạm vi AI hỗ trợ.</p></div>
      </motion.div>
    </div>
    <motion.div initial={{opacity:0,scale:.96}} whileInView={{opacity:1,scale:1}} viewport={{once:true}} className="max-w-4xl mx-auto text-center mb-20 relative"><Quote className="text-tertiary-container absolute -top-8 left-0 opacity-50" size={64} fill="currentColor"/><p className="font-headline-md text-3xl md:text-4xl font-semibold leading-relaxed px-8 text-on-surface">Công nghệ chỉ thực sự có ý nghĩa khi được dùng để học sâu hơn, sáng tạo tốt hơn và hành động có trách nhiệm hơn.</p></motion.div>
    <section className="bg-primary-container text-on-primary-container -mx-5 md:-mx-16 -mb-16 py-14 px-6 rounded-t-[3rem] text-center"><h2 className="text-display-lg mb-4">Cảm ơn bạn đã ghé thăm!</h2><p className="text-body-lg max-w-2xl mx-auto">Portfolio của Vũ Anh Mai · Ngôn ngữ Hàn Quốc · Trường Đại học Ngoại ngữ – ĐHQGHN.</p><p className="text-label-sm opacity-70 mt-8">© 2026 · Hành trình học tập số</p></section>
  </div>;
}
